[2023-04-28T09:34:40.638+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube.bulk_insert manual__2023-04-28T09:34:38.747733+00:00 [queued]>
[2023-04-28T09:34:40.645+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube.bulk_insert manual__2023-04-28T09:34:38.747733+00:00 [queued]>
[2023-04-28T09:34:40.645+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T09:34:40.645+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-28T09:34:40.645+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T09:34:40.655+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): bulk_insert> on 2023-04-28 09:34:38.747733+00:00
[2023-04-28T09:34:40.659+0000] {standard_task_runner.py:55} INFO - Started process 24322 to run task
[2023-04-28T09:34:40.661+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'youtube', 'bulk_insert', 'manual__2023-04-28T09:34:38.747733+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/youtube.py', '--cfg-path', '/tmp/tmpg1rzvzbt']
[2023-04-28T09:34:40.662+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask bulk_insert
[2023-04-28T09:34:40.712+0000] {task_command.py:389} INFO - Running <TaskInstance: youtube.bulk_insert manual__2023-04-28T09:34:38.747733+00:00 [running]> on host 9e6433510ba5
[2023-04-28T09:34:40.776+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=youtube
AIRFLOW_CTX_TASK_ID=bulk_insert
AIRFLOW_CTX_EXECUTION_DATE=2023-04-28T09:34:38.747733+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-28T09:34:38.747733+00:00
[2023-04-28T09:34:40.778+0000] {logging_mixin.py:137} INFO - <class 'str'>
[2023-04-28T09:34:40.779+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/store_comments.py", line 15, in bulk_insert
    json_docs = json.load(docs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
[2023-04-28T09:34:40.785+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=youtube, task_id=bulk_insert, execution_date=20230428T093438, start_date=20230428T093440, end_date=20230428T093440
[2023-04-28T09:34:40.792+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 52 for task bulk_insert ('str' object has no attribute 'read'; 24322)
[2023-04-28T09:34:40.833+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-28T09:34:40.848+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
